civiremote_funding.settings:
  type: config_object
  mapping:
    file_cleanup_delay:
      type: integer
      label: 'File clean up delay (seconds)'
    file_upload_valid_extensions:
      type: string
      label: 'Allowed file extensions for uploaded files, separated by space. Leave empty to allow all file extensions.'
